app/models.py
from sqlalchemy import DateTime
from flask_login import UserMixin
from db import db

class User(UserMixin, db.Model):
    __tablename__ = 'User'
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    senha = db.Column(db.String(120), nullable=False)
    documents = db.relationship('Documento', backref='User')

class Documento(db.Model):
    __tablename__ = 'Documento'
    doc_id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('User.id'), nullable=False)
    caminhoOriginal = db.Column(db.String(200), nullable=False)
    caminhoPredito = db.Column(db.String(200), nullable=True)
    nome_doc = db.Column(db.String(100), nullable=False)
    criado_em = db.Column(db.DateTime, default=db.func.current_timestamp())
    views = db.relationship('View', backref='Documento')

class View(db.Model):
    view_id = db.Column(db.Integer, primary_key=True)
    doc_id = db.Column(db.Integer, db.ForeignKey('Documento.doc_id'), nullable=False)
    caminho_view = db.Column(db.String(200), nullable=False)
    # html_content = db.Column(db.Text, nullable=False)
    # view_name = db.Column(db.String(100), nullable=False)
    criado_em = db.Column(db.DateTime, default=db.func.current_timestamp())

app/app.py
from flask import Flask, request, url_for, redirect, render_template
from flask_login import LoginManager, login_required, login_user, logout_user, current_user
from db import db
from models import *
import os
import json
import hashlib
from blueprints.auth.auth_blueprint import auth_bp
from blueprints.user.user_blueprint import user_blueprint
from blueprints.pred.pred_blueprint import pred_bp

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///fidelizaAI.db'
app.config['UPLOAD_FOLDER'] = 'static/uploads'
lm = LoginManager(app)
lm.login_view = 'auth.login'
lm.init_app(app)
app.secret_key = 'supersecretkey'
db.init_app(app)


app.register_blueprint(auth_bp)
app.register_blueprint(user_blueprint)
app.register_blueprint(pred_bp)

@lm.user_loader
def load_user(id):
    user = db.session.query(User).filter_by(id=id).first()
    return user

@app.route('/')
@app.route('/home')
def home():
    if current_user.is_authenticated:
        documento = db.session.query(Documento).filter_by(user_id=current_user.id).all()
        return render_template('index.html', documentos=documento)
    return render_template('index.html')

if __name__ == '__main__':
    with app.app_context():
        db.create_all()
    app.run(debug=True)

app/blueprints/pred/pred_blueprint.py
from flask import Blueprint, flash, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from flask_wtf import FlaskForm
from wtforms import FileField, SubmitField
from db import db
from werkzeug.utils import secure_filename
from docling.document_converter import DocumentConverter
import os
from datetime import datetime
from .processamento import predict, processo
from models import Documento
import pandas as pd
import matplotlib.pyplot as plt
import  base64

pred_bp = Blueprint('pred', __name__, template_folder='templates', url_prefix='/pred')

ALLOWED_EXTENSIONS = set(['csv'])
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def gerar_grafico(df, nome):

    data = pd.read_csv(df)
    # Exemplo de gráfico: histograma da coluna 'SalePrice'
    plt.figure(figsize=(10, 6))
    data['SalePrice'].hist(bins=30)
    plt.title('Distribuição do SalePrice')
    plt.xlabel('SalePrice')
    plt.ylabel('Frequência')

    # Salva o gráfico em um buffer
    plt.savefig(f'app/static/uploads/graficos/{nome}.png', format='png')



@pred_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part')
            return 'error'
        file = request.files['file']
        if file.filename == '':
            flash('No selected file')
            return "weee"
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            new_filename = f'{filename.rsplit(".", 1)[0]}_{timestamp}.csv'

            file_path = os.path.join('app/static/uploads/original', new_filename)
            file.save(file_path)
            
            uploadDoc = Documento(
                user_id=current_user.id,
                caminhoOriginal=file_path,
                nome_doc=new_filename
            )
            db.session.add(uploadDoc)
            db.session.commit()
            print(uploadDoc.doc_id)

            return redirect(url_for('pred.views', id=uploadDoc.doc_id)) 
        # if not ALLOWED_EXTENSIONS, return 'error'
        return 'error'
    #GET
    return render_template('upload.html')

@pred_bp.route('/view/<int:id>', methods=['GET', 'POST'])
@login_required
def views(id):
    doc = db.session.query(Documento).filter_by(doc_id=id).first()
    nome = doc.nome_doc.split('_202', 1)[0]
    if not doc:
        return 'Documento não encontrado', 404
    if request.method == 'POST':
        caminho = doc.caminhoOriginal
        predicao = predict(caminho)

        predito = processo(caminho, predicao, nome)

        doc.caminhoPredito = predito
        db.session.commit()
        # add DATA DE PREDICAO se possivel pra ver a att
        return redirect(url_for('pred.views', id=doc.doc_id)) #redireciona para a view do documento
    #get
    gerar_grafico(doc.caminhoOriginal, nome)
    fig = url_for('static', filename=f'uploads/graficos/{nome}.png')
    predito = doc.caminhoPredito

    return render_template('view.html', doc=doc, nome=nome, predito=predito, fig=fig)
    

app/blueprints/user/user_blueprint.py
from flask import Blueprint, render_template, redirect, request, url_for
from models import User
from db import db
from flask_login import current_user, login_required
import hashlib

user_blueprint = Blueprint('user', __name__, template_folder='templates', url_prefix='/user')

def hash(txt):
    hashTxt = hashlib.sha256(txt.encode('utf-8'))
    return hashTxt.hexdigest()

@user_blueprint.route('/perfil', methods=['GET', 'POST'])
@login_required
def perfil():
    if request.method == 'POST':
        nome = request.form['nome']
        email = request.form['email']
        senha_atual = request.form['senha_atual']
        print(current_user.senha)
        print(hash(senha_atual))
        if current_user.senha == hash(senha_atual):
            altUser = db.session.query(User).filter_by(id=current_user.id).first()
            altUser.nome = nome
            altUser.email = email
            
            nova_senha = request.form['nova_senha']
            if nova_senha:
                altUser.senha = hash(nova_senha)

            db.session.commit()
            return redirect(url_for('user.perfil'))
        else:
            return "Senha atual incorreta"
    # GET
    id = current_user.id
    user = db.session.query(User).filter_by(id=id).first()
    
    return render_template('perfil.html', user=user)

app/templates/header.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fideliza AI</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-light bg-light container-fluid">
        <a class="navbar-brand" href="{{ url_for('home') }}">Fideliza AI</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto mr-3">
                {% if not current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.cadastro') }}">Cadastro</a>
                        </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.perfil') }}">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/index.html
{% extends 'header.html' %}

{% block content %}
<div class="container mt-5">
    {% if current_user.is_authenticated %}
        <h1 class="text-center mb-4">Olá, {{ current_user.nome }}!</h1>
        <h1 class="mb-4">Visualizações</h1>
        <div class="d-flex flex-wrap border border-3 w-100">
            {% if documentos %}
                {% for documento in documentos %}
                    <a href="#">
                        <div class="card m-2" style="width: 18rem; cursor: pointer;">
                            <div class="card-body">
                                <h5 class="card-title">{{ documento.nome_doc.split('_202')[0] }}</h5>
                                <a href="{{ url_for('pred.views', id=documento.doc_id) }}" class="btn btn-primary mt-2">
                                    Ver detalhes
                                </a>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% endif %}
            <a href="#">
                <div class="card m-2" style="width: 18rem; cursor: pointer;">
                    <div class="card-body text-center">
                        <h5 class="card-title" style="font-size: 3rem;">+</h5>
                        <a href="{{ url_for('pred.upload') }}">Clique aqui para criar novas visualizações</a>
                    </div>
                </div>
            </a>
            </div>
        </div>
    {% else %}
        <h1 class="text-center">Seja bem vindo(a) a Fideliza.AI</h1>
        <p class="text-center mt-4">Nosso sistema serve para ajudar empresas a aumentarem a retenção de clientes por assinatura! Para isso, predizemos baseado em uma sequência de informações o que pode estar diminuindo o churn da sua empresa. Para acessar, é necessário fazer login</p>
        <div class="col mt-5 text-center">
            <a class="btn btn-primary" href="{{ url_for('auth.login') }}">Login</a>
            <a class="btn btn-primary" href="{{ url_for('auth.cadastro') }}">Cadastro</a>
        </div>
    {% endif %}
</div>
{% endblock %}